//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursor3D_Kursor3DModule {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Configuration : global::System.Configuration.ApplicationSettingsBase {
        
        private static Configuration defaultInstance = ((Configuration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Configuration())));
        
        public static Configuration Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\TheUser\\source\\repos\\Cursor 3D Module\\Kursor3D_Kursor3DModule\\Kursor3D_K" +
            "ursor3DModule\\bin\\Debug\\Sources\\GestureData\\Cursor")]
        public string CursorGestureType {
            get {
                return ((string)(this["CursorGestureType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\TheUser\\source\\repos\\Cursor 3D Module\\Kursor3D_Kursor3DModule\\Kursor3D_K" +
            "ursor3DModule\\bin\\Debug\\Sources\\GestureData\\\\Select")]
        public string SelectGestureType {
            get {
                return ((string)(this["SelectGestureType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\TheUser\\source\\repos\\Cursor 3D Module\\Kursor3D_Kursor3DModule\\Kursor3D_K" +
            "ursor3DModule\\bin\\Debug\\Sources\\GestureData\\Move")]
        public string MoveGestureType {
            get {
                return ((string)(this["MoveGestureType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\TheUser\\source\\repos\\Cursor 3D Module\\Kursor3D_Kursor3DModule\\Kursor3D_K" +
            "ursor3DModule\\bin\\Debug\\Sources\\GestureData\\Scale")]
        public string ScaleGestureType {
            get {
                return ((string)(this["ScaleGestureType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\TheUser\\source\\repos\\Cursor 3D Module\\Kursor3D_Kursor3DModule\\Kursor3D_K" +
            "ursor3DModule\\bin\\Debug\\Sources\\GestureData\\Rotate")]
        public string RotateGestureType {
            get {
                return ((string)(this["RotateGestureType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\TheUser\\source\\repos\\Cursor 3D Module\\Kursor3D_Kursor3DModule\\Kursor3D_K" +
            "ursor3DModule\\bin\\Debug\\Sources\\GestureData\\OpenMenu")]
        public string OpenMenuGestureType {
            get {
                return ((string)(this["OpenMenuGestureType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartFromApplicationPath {
            get {
                return ((bool)(this["StartFromApplicationPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartApplicationHidden {
            get {
                return ((bool)(this["StartApplicationHidden"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kursor3DImageNotifier")]
        public string NamedPipeImageServer {
            get {
                return ((string)(this["NamedPipeImageServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CursorProcessCompleteNotifier")]
        public string NamedPipeCursorAndGestureInfo {
            get {
                return ((string)(this["NamedPipeCursorAndGestureInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kursor3DSourceImage")]
        public string MemoryMappedFFileName {
            get {
                return ((string)(this["MemoryMappedFFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0002")]
        public double CursorThreshold {
            get {
                return ((double)(this["CursorThreshold"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int CursorOctaves {
            get {
                return ((int)(this["CursorOctaves"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CursorInitial {
            get {
                return ((int)(this["CursorInitial"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0002")]
        public double SelectThreshold {
            get {
                return ((double)(this["SelectThreshold"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SelectOctaves {
            get {
                return ((int)(this["SelectOctaves"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SelectInitial {
            get {
                return ((int)(this["SelectInitial"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0002")]
        public double MoveThreshold {
            get {
                return ((double)(this["MoveThreshold"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MoveOctaves {
            get {
                return ((int)(this["MoveOctaves"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MoveInitial {
            get {
                return ((int)(this["MoveInitial"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0002")]
        public double RotateThreshold {
            get {
                return ((double)(this["RotateThreshold"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RotateOctaves {
            get {
                return ((int)(this["RotateOctaves"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int RotateInitial {
            get {
                return ((int)(this["RotateInitial"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0002")]
        public double ScaleThreshold {
            get {
                return ((double)(this["ScaleThreshold"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ScaleOctaves {
            get {
                return ((int)(this["ScaleOctaves"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ScaleInitial {
            get {
                return ((int)(this["ScaleInitial"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0002")]
        public double OpenMenuThreshold {
            get {
                return ((double)(this["OpenMenuThreshold"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int OpenMenuOcaves {
            get {
                return ((int)(this["OpenMenuOcaves"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int OpenMenuInitial {
            get {
                return ((int)(this["OpenMenuInitial"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double MinHue {
            get {
                return ((double)(this["MinHue"]));
            }
            set {
                this["MinHue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54")]
        public double MinSaturation {
            get {
                return ((double)(this["MinSaturation"]));
            }
            set {
                this["MinSaturation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public double MinValue {
            get {
                return ((double)(this["MinValue"]));
            }
            set {
                this["MinValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double MaxHue {
            get {
                return ((double)(this["MaxHue"]));
            }
            set {
                this["MaxHue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53")]
        public double MaxSaturation {
            get {
                return ((double)(this["MaxSaturation"]));
            }
            set {
                this["MaxSaturation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("67")]
        public double MaxValue {
            get {
                return ((double)(this["MaxValue"]));
            }
            set {
                this["MaxValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YCrCb_LumaMin {
            get {
                return ((double)(this["YCrCb_LumaMin"]));
            }
            set {
                this["YCrCb_LumaMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("131")]
        public double YCrCb_RedMinusLumaMin {
            get {
                return ((double)(this["YCrCb_RedMinusLumaMin"]));
            }
            set {
                this["YCrCb_RedMinusLumaMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double YCrCb_BlueMinusLumaMin {
            get {
                return ((double)(this["YCrCb_BlueMinusLumaMin"]));
            }
            set {
                this["YCrCb_BlueMinusLumaMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public double YCrCb_LumaMax {
            get {
                return ((double)(this["YCrCb_LumaMax"]));
            }
            set {
                this["YCrCb_LumaMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("185")]
        public double YCrCb_RedMinusLumaMax {
            get {
                return ((double)(this["YCrCb_RedMinusLumaMax"]));
            }
            set {
                this["YCrCb_RedMinusLumaMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("135")]
        public double YCrCb_BlueMinusLumaMax {
            get {
                return ((double)(this["YCrCb_BlueMinusLumaMax"]));
            }
            set {
                this["YCrCb_BlueMinusLumaMax"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Debug {
            get {
                return ((bool)(this["Debug"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseSampleFunction {
            get {
                return ((bool)(this["UseSampleFunction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\TheUser\\Documents\\iWisoft Free Video Converter\\V_20180507_png")]
        public string SampleImageLocation {
            get {
                return ((string)(this["SampleImageLocation"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\TheUser\\Documents\\iWisoft Free Video Converter\\V_20180507_png\\V_20180507" +
            "_122151_000009.png")]
        public string SampleImageFile {
            get {
                return ((string)(this["SampleImageFile"]));
            }
            set {
                this["SampleImageFile"] = value;
            }
        }
    }
}
